import { sql } from "drizzle-orm";
import { check, index, integer, jsonb, pgTable, text, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { deviceRole, offlineReviewKind } from "./enums";
import { money, ts } from "./columns";
import { users } from "./users";
import { sales } from "./sales";

/**
 * A phone or tablet running the Android app.
 *
 * Registered the first time someone signs in on it -- Tailscale already decides
 * which devices can reach the server at all, so there is no separate pairing
 * step. The row exists so offline sales can say which device rang them, and so
 * a lost phone can be cut off.
 */
export const devices = pgTable(
  "devices",
  {
    /** Generated by the app at setup, not by the server. */
    id: uuid("id").primaryKey(),
    name: text("name").notNull(),
    role: deviceRole("role").notNull(),
    /**
     * Short and unique, printed in offline receipt numbers (`OFF-K7Q-0012`)
     * so a paper receipt names the phone that issued it.
     */
    code: text("code").notNull(),
    /** SHA-256 of the bearer token. The token itself is only ever on the phone. */
    tokenHash: text("token_hash").notNull(),
    appVersion: text("app_version"),
    registeredBy: uuid("registered_by")
      .notNull()
      .references(() => users.id),
    createdAt: ts("created_at").notNull().defaultNow(),
    lastSeenAt: ts("last_seen_at").notNull().defaultNow(),
    lastSyncAt: ts("last_sync_at"),
    /** A revoked device is refused everything. Revoked, never deleted: its sales name it. */
    revokedAt: ts("revoked_at"),
    revokedBy: uuid("revoked_by").references(() => users.id),
  },
  (t) => [
    uniqueIndex("devices_code_idx").on(t.code),
    uniqueIndex("devices_token_hash_idx").on(t.tokenHash),
    check(
      "devices_revocation_is_attributed",
      sql`(${t.revokedAt} is null) = (${t.revokedBy} is null)`,
    ),
  ],
);

/**
 * The permission to sell offline for one day.
 *
 * Issued every time the till syncs. The phone refuses to sell once its newest
 * pass has run out; the server keeps the passes so a replayed sale can be dated
 * from a time the server itself issued, and checked against the limits the
 * pass carried.
 */
export const devicePasses = pgTable(
  "device_passes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    deviceId: uuid("device_id")
      .notNull()
      .references(() => devices.id),
    issuedAt: ts("issued_at").notNull().defaultNow(),
    expiresAt: ts("expires_at").notNull(),
    maxSales: integer("max_sales").notNull(),
    maxTotal: money("max_total").notNull(),
  },
  (t) => [index("device_passes_device_idx").on(t.deviceId, t.issuedAt)],
);

/**
 * A one-time code that turns a sign-in on the app's own screen into a website
 * session inside the app's browser. Lives a minute and works once; only its
 * hash is stored.
 */
export const deviceHandoffs = pgTable(
  "device_handoffs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    codeHash: text("code_hash").notNull(),
    deviceId: uuid("device_id")
      .notNull()
      .references(() => devices.id),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    expiresAt: ts("expires_at").notNull(),
    usedAt: ts("used_at"),
    createdAt: ts("created_at").notNull().defaultNow(),
  },
  (t) => [uniqueIndex("device_handoffs_code_idx").on(t.codeHash)],
);

/**
 * An offline sale a manager has to look at.
 *
 * The medicine in an offline sale has already left the shop, so nothing the
 * phone sends is ever dropped: either it is booked, or it waits here with the
 * whole of what the phone sent. Resolved with a note, never deleted.
 */
export const offlineSaleReviews = pgTable(
  "offline_sale_reviews",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    kind: offlineReviewKind("kind").notNull(),
    deviceId: uuid("device_id")
      .notNull()
      .references(() => devices.id),
    /** The app's id for the sale; a resend of a sale waiting here is recognised by it. */
    clientId: uuid("client_id").notNull(),
    offlineNumber: text("offline_number").notNull(),
    cashierId: uuid("cashier_id")
      .notNull()
      .references(() => users.id),
    soldAt: ts("sold_at").notNull(),
    /** Set once booked -- straight away for `flagged`, on a later retry for `not_posted`. */
    saleId: uuid("sale_id").references(() => sales.id),
    /** Why: an error code for `not_posted`, the flags for `flagged`. */
    reasons: jsonb("reasons").$type<string[]>().notNull(),
    /** Everything the phone sent, so a retry needs nothing from the phone. */
    payload: jsonb("payload").notNull(),
    createdAt: ts("created_at").notNull().defaultNow(),
    resolvedAt: ts("resolved_at"),
    resolvedBy: uuid("resolved_by").references(() => users.id),
    resolutionNote: text("resolution_note"),
  },
  (t) => [
    uniqueIndex("offline_sale_reviews_client_idx").on(t.clientId),
    index("offline_sale_reviews_open_idx").on(t.createdAt).where(sql`${t.resolvedAt} is null`),
    check(
      "offline_sale_reviews_resolution_is_explained",
      sql`(${t.resolvedAt} is null) or (${t.resolvedBy} is not null and ${t.resolutionNote} is not null)`,
    ),
    check(
      "offline_sale_reviews_flagged_is_booked",
      sql`${t.kind} <> 'flagged' or ${t.saleId} is not null`,
    ),
  ],
);
