/**
 * The contract between the server and the Android app.
 *
 * Types only, plus a few constants: the app bundles this file (it imports
 * nothing), so both sides compile against one description of every request
 * and response under `/api/device/*`. A field renamed here fails the build on
 * both sides instead of failing at the counter.
 *
 * Every route answers JSON and allows the app's own origin
 * (`https://localhost`) through CORS. The app authenticates with
 * `Authorization: Bearer <deviceToken>` -- except `ping` (open) and `login`
 * (which is where the token comes from).
 */

export const APP_ORIGINS = ["https://localhost", "http://localhost", "capacitor://localhost"] as const;

/** Where the app serves its own screens, inside the phone. */
export const APP_SHELL = "https://localhost";

/** Appended to the WebView's user agent, so the website knows it is inside the app. */
export const APP_USER_AGENT_MARK = "PharmacyLedgerApp/";

/** How long an offline pass lasts: the app must reach the server at least this often. */
export const PASS_HOURS = 24;

/** How long a staff member may sign in offline after their last online sign-in on the device. */
export const OFFLINE_SIGN_IN_HOURS = 24;

export type DeviceRole = "till" | "management";

export const PAYMENT_METHODS = [
  "tunai",
  "kartu_debit",
  "kartu_kredit",
  "qris",
  "transfer",
  "lainnya",
] as const;
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

/* ------------------------------------------------------------------ errors */

/** Every non-2xx response has this body. */
export type ApiError = {
  error:
    | "invalid" // wrong username or password
    | "locked" // too many attempts; see `minutes`
    | "suspended"
    | "device_revoked" // the owner removed this device; set it up again
    | "unauthorized" // missing or unknown device token
    | "not_till" // a management device asked for till data
    | "bad_request";
  minutes?: number;
};

/* -------------------------------------------------------- GET /api/device/ping */

export type PingResponse = {
  ok: true;
  app: "pharmacy-stock-ledger";
  version: string;
  businessName: string;
  /** Server time, ISO. */
  serverTime: string;
};

/* ------------------------------------------------------ POST /api/device/login */

export type LoginRequest = {
  /** Generated by the app once, at setup. */
  deviceId: string;
  deviceName: string;
  role: DeviceRole;
  username: string;
  password: string;
  appVersion: string;
};

export type DeviceUser = {
  id: string;
  username: string;
  fullName: string;
  locale: "id" | "en";
  isOwner: boolean;
  isPharmacist: boolean;
  /** Owners hold every permission; the list is complete for them too. */
  permissions: string[];
  /**
   * Changes whenever the password does. The app throws away its offline
   * verifier for a user whose stamp moved, so an old password stops working
   * offline once the phone has synced.
   */
  credentialStamp: string;
};

export type LoginResponse = {
  /** Present only when the server has just issued one: store it. */
  deviceToken?: string;
  device: { id: string; name: string; role: DeviceRole; code: string };
  user: DeviceUser & { mustChangePassword: boolean };
  /** Server time of this sign-in, ISO. Offline sign-in is measured from it. */
  serverTime: string;
  /**
   * Single use, valid for 60 seconds. Open
   * `${server}/api/device/handoff?code=${code}` in the WebView to arrive
   * signed in to the website.
   */
  handoffCode: string;
};

/* --------------------------------------------------- POST /api/device/snapshot */

export type SnapshotRequest = {
  /** Users the app holds offline credentials for; their current state comes back. */
  userIds: string[];
};

export type SnapshotItem = {
  id: string;
  code: string;
  genericName: string;
  brandName: string | null;
  strength: string | null;
  unit: string;
  drugClass: string;
  /** Sell price, whole rupiah. */
  price: number;
  isTaxExempt: boolean;
  barcodes: string[];
  /** Active batches holding stock. Expired ones are included: the till refuses them itself. */
  batches: Array<{ id: string; lotNumber: string | null; expiryDate: string; qty: number }>;
};

export type OfflinePass = {
  id: string;
  /** Server time, ISO. */
  issuedAt: string;
  expiresAt: string;
  maxSales: number;
  /** Whole rupiah across all offline sales under this pass. */
  maxTotal: number;
};

export type SnapshotResponse = {
  serverTime: string;
  /** Today in the pharmacy's timezone, YYYY-MM-DD. */
  serverToday: string;
  settings: {
    businessName: string;
    businessAddress: string | null;
    businessPhone: string | null;
    npwp: string | null;
    licenceNumber: string | null;
    receiptFooter: string | null;
    receiptLocale: "id" | "en";
    timezone: string;
    currencyCode: string;
    currencyDecimals: number;
  };
  /** The rate in force today, or null when the pharmacy charges no PPN. */
  tax: { mode: "inclusive" | "exclusive"; rateBps: number } | null;
  items: SnapshotItem[];
  /** One entry per requested id that still exists. Inactive users must be forgotten. */
  users: Array<DeviceUser & { active: boolean }>;
  pass: OfflinePass;
  device: { id: string; name: string; role: DeviceRole; code: string };
};

/* ------------------------------------------------------- POST /api/device/sync */

export type OfflineSale = {
  /** UUID made by the app. Sending the same sale twice posts it once. */
  clientId: string;
  /** Printed on the customer's receipt: `OFF-<device code>-<seq>`. */
  offlineNumber: string;
  /** The pass the sale was made under. */
  passId: string;
  /**
   * Milliseconds between receiving that pass and ringing the sale, measured on
   * the phone's monotonic clock (which changing the date cannot move). The
   * server dates the sale as `pass.issuedAt + elapsedMs`.
   */
  elapsedMs: number;
  /** The phone's wall clock at the sale, ISO. Informational only. */
  deviceTime: string;
  cashierId: string;
  lines: Array<{ itemId: string; qty: number; unitPrice: number }>;
  discount: number;
  paymentMethod: PaymentMethod;
  tendered: number | null;
  notes: string | null;
  /** What the app charged; compared with what the server books. */
  total: number;
};

export type SyncRequest = { sales: OfflineSale[] };

export type SyncResult = {
  clientId: string;
  /**
   * posted    -- booked; `saleNumber` is its real number.
   * review    -- could not be booked as it stands, or was booked with
   *              something a manager should look at. Either way the app is
   *              done with it: it is on the server's review list.
   * duplicate -- already received earlier; `saleNumber` if it was booked.
   */
  status: "posted" | "review" | "duplicate";
  saleNumber?: string;
  flags: string[];
};

export type SyncResponse = { results: SyncResult[] };
